server:
  port: 18085
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.190.155.151:3306/pmall
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
      # password: ''  如果没有设置密码，这里不写
    timeout: 3s
mybatis:
  mapper-locations: classpath:mapper/*.xml
nacos:
  config:
    server-addr: 127.0.0.1:8848